import "./style.css";

import { fetchSceneAndMount_scene_01 } from "./polygonjs/scenes/scene_01/autogenerated/fetchSceneAndMount";
import { fetchSceneAndMount_torus_knot } from "./polygonjs/scenes/torus_knot/autogenerated/fetchSceneAndMount";
import { fetchSceneAndMount_scene_sphere } from "./polygonjs/scenes/scene_sphere/autogenerated/fetchSceneAndMount";

// fetchSceneAndMount_scene_01({
// 	domElement: "scene_01",
// });

//
// fetchSceneAndMount_torus_knot({
// 	domElement: "scene_02",
// });

fetchSceneAndMount_scene_sphere({
	domElement: "scene_02",
});